
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class AcessClassesGUI extends javax.swing.JFrame {

    /**
     * Creates new form AcessClassesGUI
     */
    
    private Student Students;
    private String TeacherName;
    private String CourseName;
    
    public AcessClassesGUI(String ClassNumber, String TeacherName, String Coursename) throws FileNotFoundException {
        Students = new Student(ClassNumber);
        this.TeacherName = TeacherName;
        this.CourseName = Coursename;
        initComponents();
        this.setSize(783, 470);
        SearchERPLabel.setVisible(false);
        NameLabel.setVisible(false);
        COPLabel.setVisible(false);
        SearchERPTextField.setVisible(false);
        NameTextField.setVisible(false);
        COPTextField.setVisible(false);
        SearchButton.setVisible(false);
        
        EditERPLabel.setVisible(false);
        NOPLabel.setVisible(false);
        EditRecordERP.setVisible(false);
        NOPTextField.setVisible(false);
        EditButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchByIDButton = new java.awt.Button();
        EditRecordButton = new java.awt.Button();
        PrintButton = new java.awt.Button();
        SearchERPLabel = new java.awt.Label();
        SearchERPTextField = new java.awt.TextField();
        NameLabel = new java.awt.Label();
        NameTextField = new java.awt.TextField();
        COPLabel = new java.awt.Label();
        COPTextField = new java.awt.TextField();
        EditERPLabel = new java.awt.Label();
        NOPLabel = new java.awt.Label();
        EditRecordERP = new java.awt.TextField();
        NOPTextField = new java.awt.TextField();
        SearchButton = new java.awt.Button();
        EditButton = new java.awt.Button();
        BackButton = new java.awt.Button();
        FENButton = new java.awt.Button();
        SignOutButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchByIDButton.setLabel("Search By ID");
        SearchByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchByIDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 136, 106, 35));

        EditRecordButton.setLabel("Edit Record");
        EditRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 136, 106, 35));

        PrintButton.setLabel("Print Students");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 136, 106, 35));

        SearchERPLabel.setName(""); // NOI18N
        SearchERPLabel.setText("ERP");
        getContentPane().add(SearchERPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 216, -1, -1));

        SearchERPTextField.setText("e.g 19734");
        getContentPane().add(SearchERPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 216, -1, -1));

        NameLabel.setText("Name");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 257, -1, -1));

        NameTextField.setEditable(false);
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 257, 130, -1));

        COPLabel.setName(""); // NOI18N
        COPLabel.setText("C.O.P");
        getContentPane().add(COPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 299, -1, -1));

        COPTextField.setEditable(false);
        getContentPane().add(COPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 299, 60, -1));

        EditERPLabel.setName(""); // NOI18N
        EditERPLabel.setText("ERP");
        getContentPane().add(EditERPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, -1, -1));

        NOPLabel.setText("N.O.P.");
        getContentPane().add(NOPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        EditRecordERP.setText("e.g 19734");
        getContentPane().add(EditRecordERP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        NOPTextField.setText("e.g. 90");
        getContentPane().add(NOPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 50, -1));

        SearchButton.setLabel("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        EditButton.setLabel("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        BackButton.setLabel("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        FENButton.setLabel("Generate and Display Final exam Numbers");
        FENButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FENButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FENButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 260, 40));

        SignOutButton.setLabel("Sign Out");
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 790, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRecordButtonActionPerformed
        
        SearchERPLabel.setVisible(false);
        NameLabel.setVisible(false);
        COPLabel.setVisible(false);
        SearchERPTextField.setVisible(false);
        NameTextField.setVisible(false);
        COPTextField.setVisible(false);
        SearchButton.setVisible(false);
        
        EditERPLabel.setVisible(true);
        NOPLabel.setVisible(true);
        EditRecordERP.setVisible(true);
        NOPTextField.setVisible(true);
        EditButton.setVisible(true);
        
    }//GEN-LAST:event_EditRecordButtonActionPerformed

    private void SearchByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIDButtonActionPerformed
        
        EditERPLabel.setVisible(false);
        NOPLabel.setVisible(false);
        EditRecordERP.setVisible(false);
        NOPTextField.setVisible(false);
        EditButton.setVisible(false);
        
        SearchERPLabel.setVisible(true);
        NameLabel.setVisible(true);
        COPLabel.setVisible(true);
        SearchERPTextField.setVisible(true);
        NameTextField.setVisible(true);
        COPTextField.setVisible(true);
        SearchButton.setVisible(true);
        
        
    }//GEN-LAST:event_SearchByIDButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        
        if(SearchERPTextField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill the required fields");
        else{
            
            try {
                if(Students.searchByERP(SearchERPTextField.getText()) == null){
                   JOptionPane.showMessageDialog(null,"Student not found");     
                }
                else{
                    JOptionPane.showMessageDialog(null,"Student found");
                    NameTextField.setText(Students.searchByERP(SearchERPTextField.getText()).key.studentName);
                    COPTextField.setText(Students.searchByERP(SearchERPTextField.getText()).key.currentOverallPercentage);
                }
                    
                } catch (FileNotFoundException ex) {
                Logger.getLogger(AcessClassesGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        
        if(EditRecordERP.getText().equals("") || NOPTextField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill the required fields");
        else{
            
            try {
                if(Students.searchByERP(EditRecordERP.getText()) == null)
                   JOptionPane.showMessageDialog(null,"No such ERP exists"); 
                else{
                    JOptionPane.showMessageDialog(null,"ERP found and changed");
                    Students.editRecord(EditRecordERP.getText(), NOPTextField.getText());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AcessClassesGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }   
        
        
        
    }//GEN-LAST:event_EditButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        
        PrintStudentsGUI printAll;
        try {
            printAll = new PrintStudentsGUI(Students,TeacherName,CourseName);
            printAll.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AcessClassesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        try {
            ClassDisplayGUI Classes = new ClassDisplayGUI(TeacherName, CourseName);
            Classes.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AcessClassesGUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void FENButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FENButtonActionPerformed
        
        FENGUI DisplayFENs;
        try {
            DisplayFENs = new FENGUI(Students.classNumber, TeacherName, CourseName);
            DisplayFENs.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AcessClassesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_FENButtonActionPerformed

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        
        Login_GUI signout = new Login_GUI();
        signout.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_SignOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcessClassesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcessClassesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcessClassesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcessClassesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new AcessClassesGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BackButton;
    private java.awt.Label COPLabel;
    private java.awt.TextField COPTextField;
    private java.awt.Button EditButton;
    private java.awt.Label EditERPLabel;
    private java.awt.Button EditRecordButton;
    private java.awt.TextField EditRecordERP;
    private java.awt.Button FENButton;
    private java.awt.Label NOPLabel;
    private java.awt.TextField NOPTextField;
    private java.awt.Label NameLabel;
    private java.awt.TextField NameTextField;
    private java.awt.Button PrintButton;
    private java.awt.Button SearchButton;
    private java.awt.Button SearchByIDButton;
    private java.awt.Label SearchERPLabel;
    private java.awt.TextField SearchERPTextField;
    private java.awt.Button SignOutButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
