
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class AddClassGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddClassGUI
     */
    
    private ClassAccessView CAV = new ClassAccessView();
    private String ClassNumber;
    
    private SinglyLinkList StudenstToAdd = new SinglyLinkList();
    private ArrayList<String> StudentNames = new ArrayList<String>();
    private ArrayList<String> StudentIDs = new ArrayList<String>();
    
    public AddClassGUI(ClassAccessView CAV) {
        this.CAV = CAV;
        initComponents();
        SNTextField.setEditable(false);
        IDTextField.setEditable(false);
        CPTextField.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new java.awt.Button();
        CNLabel = new javax.swing.JLabel();
        SNLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        CNTextField = new java.awt.TextField();
        SNTextField = new java.awt.TextField();
        IDTextField = new java.awt.TextField();
        CPTextField = new java.awt.TextField();
        CPLabel = new javax.swing.JLabel();
        AddStudentButton = new java.awt.Button();
        DoneButton = new java.awt.Button();
        ConfirmClassButton = new java.awt.Button();
        CancelButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        button2.setLabel("button2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CNLabel.setText("Class Name");
        getContentPane().add(CNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 70, -1, -1));

        SNLabel.setText("Name");
        getContentPane().add(SNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 131, -1, -1));

        IDLabel.setText("ID");
        getContentPane().add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 195, -1, -1));

        CNTextField.setText("eg. 2508");
        getContentPane().add(CNTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 70, -1, -1));

        SNTextField.setName(""); // NOI18N
        SNTextField.setText("eg. Rafay Tanweer");
        getContentPane().add(SNTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 127, 142, -1));

        IDTextField.setText("eg. 19734");
        getContentPane().add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 195, -1, -1));

        CPTextField.setText("eg. 85");
        getContentPane().add(CPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 250, -1, -1));

        CPLabel.setText("Current Percentage");
        getContentPane().add(CPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 254, -1, -1));

        AddStudentButton.setLabel("Add");
        AddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 318, -1, -1));

        DoneButton.setLabel("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 318, -1, -1));

        ConfirmClassButton.setLabel("Confirm");
        ConfirmClassButton.setName(""); // NOI18N
        ConfirmClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmClassButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmClassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 70, -1, -1));

        CancelButton.setLabel("Back/Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 397, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmClassButtonActionPerformed
        
        if(CNTextField.getText() == "")
            JOptionPane.showMessageDialog(null,"Please enter the required field");
        else{
            this.ClassNumber = CNTextField.getText();
            CNTextField.setEditable(false);
            SNTextField.setEditable(true);
            IDTextField.setEditable(true);
            CPTextField.setEditable(true);
        }
        
    }//GEN-LAST:event_ConfirmClassButtonActionPerformed

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        
        boolean check = true;
        boolean check2 = true;
        if(SNTextField.getText() == "" || IDTextField.getText() == "" || CPTextField.getText() == "")
            JOptionPane.showMessageDialog(null,"Please enter the required field");
        else{
            for(int i  = 0; i < this.StudentNames.size(); i++){
            
                if(this.StudentNames.get(i).equals(SNTextField.getText())){
                    check = false;
                    break;
                }
                
            }
            
            for(int i = 0; i < this.StudentIDs.size(); i++){
                
                if(this.StudentIDs.get(i).equals(IDTextField.getText())){
                    check2 = false;
                    break;
                }
                
            }
        
            if(check == true && check2 == true){
                StudentNames.add(SNTextField.getText());
                StudentIDs.add(IDTextField.getText());
                this.StudenstToAdd.addAtEnd(SNTextField.getText(), IDTextField.getText(), Double.parseDouble(CPTextField.getText()));
            }
            else
                JOptionPane.showMessageDialog(null,"The Student or ID you are trying to enter has already been added");
        }
        
        
        
        
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        
        if(StudenstToAdd.countNodes() == 0)
            JOptionPane.showMessageDialog(null,"List of Students to add is empty");
        else{
            try {
                CAV.CreateClass(ClassNumber, StudenstToAdd);
                JOptionPane.showMessageDialog(null,"Class created successfully");
                new CAVGUI(this.CAV.TeacherName, this.CAV.CourseName).setVisible(true);
                this.setVisible(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AddClassGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        
        new CAVGUI(this.CAV.TeacherName, this.CAV.CourseName).setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new AddClassGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AddStudentButton;
    private javax.swing.JLabel CNLabel;
    private java.awt.TextField CNTextField;
    private javax.swing.JLabel CPLabel;
    private java.awt.TextField CPTextField;
    private java.awt.Button CancelButton;
    private java.awt.Button ConfirmClassButton;
    private java.awt.Button DoneButton;
    private javax.swing.JLabel IDLabel;
    private java.awt.TextField IDTextField;
    private javax.swing.JLabel SNLabel;
    private java.awt.TextField SNTextField;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
