
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class CAVGUI extends javax.swing.JFrame {

    /**
     * Creates new form CAVGUI
     */
    

    private ClassAccessView CAV = new ClassAccessView();
    
    public CAVGUI(String TeacherName, String CourseName) {
        this.CAV.TeacherName = TeacherName;
        this.CAV.CourseName = CourseName;
        initComponents();
        ClassToDeleteLabel.setVisible(false);
        DelClassNumField.setVisible(false);
        DeleteButton.setVisible(false);
        this.setSize(630, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AddClassButton = new java.awt.Button();
        DelClassButton = new java.awt.Button();
        AccessClassesButton = new java.awt.Button();
        ClassToDeleteLabel = new java.awt.Label();
        DelClassNumField = new java.awt.TextField();
        DeleteButton = new java.awt.Button();
        BackButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddClassButton.setLabel("Add Class");
        AddClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClassButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddClassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 125, 95, 41));

        DelClassButton.setLabel("Delete Class");
        DelClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelClassButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DelClassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 125, 91, 41));

        AccessClassesButton.setLabel("Access Classes");
        AccessClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessClassesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AccessClassesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 125, 94, 41));

        ClassToDeleteLabel.setText("Class Number");
        getContentPane().add(ClassToDeleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 219, -1, -1));

        DelClassNumField.setText("eg. 2508");
        getContentPane().add(DelClassNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 219, -1, -1));

        DeleteButton.setLabel("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 249, -1, -1));

        BackButton.setLabel("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClassButtonActionPerformed
        
        AddClassGUI AddClass = new AddClassGUI(CAV);
        AddClass.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AddClassButtonActionPerformed

    private void DelClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelClassButtonActionPerformed
        
        ClassToDeleteLabel.setVisible(true);
        DelClassNumField.setVisible(true);
        DeleteButton.setVisible(true);
        
    }//GEN-LAST:event_DelClassButtonActionPerformed

    private void AccessClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessClassesButtonActionPerformed

        ClassDisplayGUI DisplayClasses;
        try {
            DisplayClasses = new ClassDisplayGUI(this.CAV.TeacherName, this.CAV.CourseName);
            DisplayClasses.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CAVGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_AccessClassesButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        
        if(DelClassNumField.getText() == "")
            JOptionPane.showMessageDialog(null,"Please enter the required field");
        else{
            try {
                if(CAV.DeleteClass(DelClassNumField.getText())){
                    JOptionPane.showMessageDialog(null,"Class Deleted successfully");
                    ClassToDeleteLabel.setVisible(false);
                    DelClassNumField.setVisible(false);
                    DeleteButton.setVisible(false);
                }
            
                else
                    JOptionPane.showMessageDialog(null,"The Class doesnt exist, please try again");
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(CAVGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        new CODandCAVGUI(this.CAV.TeacherName, this.CAV.CourseName).setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new CAVGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AccessClassesButton;
    private java.awt.Button AddClassButton;
    private java.awt.Button BackButton;
    private java.awt.Label ClassToDeleteLabel;
    private java.awt.Button DelClassButton;
    private java.awt.TextField DelClassNumField;
    private java.awt.Button DeleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
