
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class CODandCAVGUI extends javax.swing.JFrame {

    /**
     * Creates new form CODandCAVGUI
     */
    
    private String TeacherName;
    private String CourseName;
    
    public CODandCAVGUI(String TeacherName, String CourseName) {
        this.TeacherName = TeacherName;
        this.CourseName = CourseName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        label1 = new java.awt.Label();
        CODbutton = new javax.swing.JButton();
        CAVbutton = new javax.swing.JButton();
        BackButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        button1.setLabel("button1");

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CODbutton.setText("Course Outline Designer");
        CODbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(CODbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 146, 197, 50));

        CAVbutton.setText("Class Access View");
        CAVbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAVbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(CAVbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 146, 197, 50));

        BackButton.setLabel("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 282, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CODbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODbuttonActionPerformed
        
        CODGUI CourseDesigner = new CODGUI(TeacherName, CourseName);
        CourseDesigner.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_CODbuttonActionPerformed

    private void CAVbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAVbuttonActionPerformed
        
        CAVGUI CAVHome = new CAVGUI(TeacherName,CourseName);
        this.setVisible(false);
        CAVHome.setVisible(true);
        
        
        
    }//GEN-LAST:event_CAVbuttonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        Login Account = new Login();
        Account.Username = this.TeacherName;
        try {
            new CourseDisplayGUI(Account).setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CODandCAVGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CODandCAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CODandCAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CODandCAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CODandCAVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new CODandCAVGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BackButton;
    private javax.swing.JButton CAVbutton;
    private javax.swing.JButton CODbutton;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
