
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class CODGUI extends javax.swing.JFrame {

    /**
     * Creates new form CODGUI
     */
    
    private String TeacherName;
    private String CourseName;
    
    public CODGUI(String TeacherName, String CourseName) {
        this.TeacherName = TeacherName;
        this.CourseName = CourseName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WeightageButton = new java.awt.Button();
        MaxNumbersButton = new java.awt.Button();
        COButton = new java.awt.Button();
        BackButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WeightageButton.setLabel("Weightages");
        WeightageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(WeightageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 131, 97, 33));

        MaxNumbersButton.setLabel("Max Numbers");
        MaxNumbersButton.setName(""); // NOI18N
        MaxNumbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxNumbersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MaxNumbersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 131, 97, 33));

        COButton.setLabel("Course Overview");
        COButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COButtonActionPerformed(evt);
            }
        });
        getContentPane().add(COButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 131, 99, 33));

        BackButton.setLabel("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WeightageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightageButtonActionPerformed
        
        DesignerGUI WeightageGUI;
        try {
            WeightageGUI = new DesignerGUI(TeacherName, CourseName, "Weightages");
            WeightageGUI.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CODGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_WeightageButtonActionPerformed

    private void MaxNumbersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxNumbersButtonActionPerformed
        
        DesignerGUI MaxNumbersGUI;
        try {
            MaxNumbersGUI = new DesignerGUI(TeacherName, CourseName, "MaxNumbers");
            MaxNumbersGUI.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CODGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MaxNumbersButtonActionPerformed

    private void COButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COButtonActionPerformed
        
        DesignerGUI CourseOverViewGUI;
        try {
            CourseOverViewGUI = new DesignerGUI(TeacherName, CourseName, "CourseOverview");
            CourseOverViewGUI.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CODGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_COButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        CODandCAVGUI CODCAV = new CODandCAVGUI(TeacherName, CourseName);
        CODCAV.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CODGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CODGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CODGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CODGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new CODGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BackButton;
    private java.awt.Button COButton;
    private java.awt.Button MaxNumbersButton;
    private java.awt.Button WeightageButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
