
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class FENGUI extends javax.swing.JFrame {

    /**
     * Creates new form FENGUI
     */
    
    private String ClassNumber;
    private String TeacherName;
    private String CourseName;
    private FENumberGen Generator;
    
    public FENGUI(String ClassNumber, String TeacherName, String CourseName) throws FileNotFoundException {
        this.ClassNumber = ClassNumber;
        this.TeacherName = TeacherName;
        this.CourseName = CourseName;
        this.Generator = new FENumberGen(this.ClassNumber);
        initComponents();
        this.label2.setText(this.ClassNumber);
        DisplayFEN();
    }
    
    public void DisplayFEN() throws FileNotFoundException{
        
        DefaultTableModel model = (DefaultTableModel) FENJtable.getModel();
        File FENFile = new File("FEN" + ClassNumber + ".txt");
        ArrayList<FENRecord> FENs;
        if(FENFile.exists()){
            FENs = Generator.getFENs();
            for(int i = 0; i < FENs.size(); i++){
                
                Object[] RowArray = new Object[3];
                RowArray[0] = FENs.get(i).Name;
                RowArray[1] = FENs.get(i).ID;
                RowArray[2] = FENs.get(i).FEN;
                
                model.addRow(RowArray);
            }
        }
        else{
            
            Generator.CreatingHashTableAndFENFile();
            FENs = Generator.getFENs();
            for(int i = 0; i < FENs.size(); i++){
                
                Object[] RowArray = new Object[3];
                RowArray[0] = FENs.get(i).Name;
                RowArray[1] = FENs.get(i).ID;
                RowArray[2] = FENs.get(i).FEN;
                
                model.addRow(RowArray);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FENJtable = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        BackButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FENJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ERP", "Final Exam Number"
            }
        ));
        jScrollPane1.setViewportView(FENJtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 135, -1, 155));

        label1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        label1.setText("Final Exam Numbers for class: ");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 72, 233, -1));

        label2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        label2.setText("label2");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 72, -1, -1));

        BackButton.setLabel("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 365, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 700, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        AcessClassesGUI ACHome;
        try {
            ACHome = new AcessClassesGUI(ClassNumber, TeacherName, CourseName);
            ACHome.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FENGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FENGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FENGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FENGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FENGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
                //new FENGUI().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BackButton;
    private javax.swing.JTable FENJtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
